10:45:12 -     INFO - wally           - All info would be stored into /home/mosorio/wally/wally_results/caring_lemur
10:45:12 -     INFO - wally           - Start discover_stage
10:45:12 -     INFO - wally           - Start reuse_vms_stage
10:45:12 -     INFO - wally           - Start log_nodes_statistic_stage
10:45:12 -     INFO - wally           - Found 1 nodes total
10:45:12 -    DEBUG - wally           - Found 1 nodes with role testnode
10:45:12 -     INFO - wally           - Start save_nodes_stage
10:45:12 -     INFO - wally           - Start connect_stage
10:45:12 -     INFO - wally           - Connecting to nodes
10:45:12 -     INFO - wally           - All nodes connected successfully
10:45:12 -     INFO - wally           - Start run_tests_stage
10:45:12 -    DEBUG - wally           - Run preparation
10:45:14 -    DEBUG - wally           - prefill is skipped
10:45:14 -     INFO - wally           - Entire test should takes aroud: 0:50:03 and finished at 11:35:17
10:45:14 -     INFO - wally           - Will run ceph_rws4kth1 test
10:45:14 -     INFO - wally           - Test should takes about 0:03:30. Should finish at 10:48:44, will wait at most till 10:53:44
10:45:14 -    DEBUG - wally           - SSH:172.19.1.1:22 Exec 'screen -S test -d -m sudo bash /tmp/wally/caring_lemur/io/cmd.sh'
10:48:48 -    DEBUG - wally           - Test on node 172.19.1.1_22 is finished
10:48:48 -     INFO - wally           - Will run ceph_rws4kth5 test
10:48:48 -     INFO - wally           - Test should takes about 0:03:30. Should finish at 10:52:18, will wait at most till 10:57:18
10:48:48 -    DEBUG - wally           - SSH:172.19.1.1:22 Exec 'screen -S test -d -m sudo bash /tmp/wally/caring_lemur/io/cmd.sh'
10:52:22 -    DEBUG - wally           - Test on node 172.19.1.1_22 is finished
10:52:22 -     INFO - wally           - Will run ceph_rws4kth10 test
10:52:22 -     INFO - wally           - Test should takes about 0:03:30. Should finish at 10:55:52, will wait at most till 11:00:52
10:52:23 -    DEBUG - wally           - SSH:172.19.1.1:22 Exec 'screen -S test -d -m sudo bash /tmp/wally/caring_lemur/io/cmd.sh'
18:18:18 -     INFO - wally           - All info would be stored into /home/mosorio/wally/wally_results/caring_lemur
18:18:18 -     INFO - wally           - Start load_data_from_path_stage
18:18:18 -    ERROR - wally           - During load_data_from_path_stage
Traceback (most recent call last):
  File "wally/main.py", line 125, in log_stage
    yield
  File "wally/main.py", line 277, in main
    stage(cfg, ctx)
  File "wally/run_test.py", line 607, in load_data_from_path_stage
    for tp, vals in load_data_from_path(var_dir).items():
  File "wally/run_test.py", line 594, in load_data_from_path
    raw_res = yaml_load(open(files['raw_results']).read())
IOError: [Errno 2] No such file or directory: 'wally_results/caring_lemur/raw_results.yaml'
18:18:18 -    DEBUG - wally           - Start utils.cleanup
18:18:18 -     INFO - wally           - All info stored into /home/mosorio/wally/wally_results/caring_lemur
18:18:18 -    ERROR - wally           - Tests are failed. See detailed error above
18:20:21 -     INFO - wally           - All info would be stored into /home/mosorio/wally/wally_results/caring_lemur
18:20:21 -     INFO - wally           - Start load_data_from_path_stage
18:20:21 -    ERROR - wally           - During load_data_from_path_stage
Traceback (most recent call last):
  File "wally/main.py", line 125, in log_stage
    yield
  File "wally/main.py", line 277, in main
    stage(cfg, ctx)
  File "wally/run_test.py", line 607, in load_data_from_path_stage
    for tp, vals in load_data_from_path(var_dir).items():
  File "wally/run_test.py", line 594, in load_data_from_path
    raw_res = yaml_load(open(files['raw_results']).read())
IOError: [Errno 2] No such file or directory: 'wally_results/caring_lemur/raw_results.yaml'
18:20:21 -    DEBUG - wally           - Start utils.cleanup
18:20:21 -     INFO - wally           - All info stored into /home/mosorio/wally/wally_results/caring_lemur
18:20:21 -    ERROR - wally           - Tests are failed. See detailed error above
