14:24:38 -     INFO - wally           - All info would be stored into /home/mosorio/wally/wally_results/living_hyena
14:24:38 -     INFO - wally           - Start discover_stage
14:24:38 -     INFO - wally           - Start reuse_vms_stage
14:24:38 -     INFO - wally           - Start log_nodes_statistic_stage
14:24:38 -     INFO - wally           - Found 1 nodes total
14:24:38 -    DEBUG - wally           - Found 1 nodes with role testnode
14:24:38 -     INFO - wally           - Start save_nodes_stage
14:24:38 -     INFO - wally           - Start connect_stage
14:24:38 -     INFO - wally           - Connecting to nodes
14:24:39 -     INFO - wally           - All nodes connected successfully
14:24:39 -     INFO - wally           - Start run_tests_stage
14:24:39 -    DEBUG - wally           - Run preparation
14:24:39 -     INFO - wally           - Prefilling file /root/test.raw
14:24:40 -    DEBUG - wally           - SSH:138.219.231.195:2121 Exec 'sudo fio --name=xxx --filename=/root/test.raw --direct=1 --bs=4m --size=109m --rw=write'
14:24:40 -     INFO - wally           - Entire test should takes aroud: 0:16:30 and finished at 14:41:10
14:24:40 -     INFO - wally           - Will run hdd_rwx4kth1 test
14:24:40 -     INFO - wally           - Test should takes about 0:02:30. Should finish at 14:27:10, will wait at most till 14:32:10
14:24:41 -    DEBUG - wally           - SSH:138.219.231.195:2121 Exec 'screen -S test -d -m sudo bash /tmp/wally/living_hyena/io/cmd.sh'
14:27:13 -    DEBUG - wally           - Test on node 138.219.231.195_2121 is finished
14:27:14 -    ERROR - wally           - During run_tests_stage
Traceback (most recent call last):
  File "wally/main.py", line 125, in log_stage
    yield
  File "wally/main.py", line 277, in main
    stage(cfg, ctx)
  File "wally/run_test.py", line 481, in run_tests_stage
    for tp, res in run_tests(cfg, test_group, ctx.nodes):
  File "wally/run_test.py", line 242, in run_tests
    res = test_cls(test_cfg).run()
  File "wally/suits/io/fio.py", line 765, in run
    res = load_test_results(self.config.log_directory, pos)
  File "wally/suits/io/fio.py", line 131, in load_test_results
    ts = load_sys_log_file(ftype, os.path.join(folder, fname))
  File "wally/suits/io/fio.py", line 89, in load_sys_log_file
    return TimeSeriesValue(vals)
  File "wally/suits/itest.py", line 116, in __init__
    assert len(data) > 0
AssertionError
14:27:14 -     INFO - wally           - Start disconnect_stage
14:27:14 -    DEBUG - wally           - Start utils.cleanup
14:27:14 -     INFO - wally           - All info stored into /home/mosorio/wally/wally_results/living_hyena
14:27:14 -    ERROR - wally           - Tests are failed. See detailed error above
