16:36:44 -     INFO - wally           - All info would be stored into /var/wally_results/unminuted_velda
16:36:44 -     INFO - wally           - Start discover_stage
16:36:44 -     INFO - wally           - Start reuse_vms_stage
16:36:44 -     INFO - wally           - Start log_nodes_statistic_stage
16:36:44 -     INFO - wally           - Found 1 nodes total
16:36:44 -    DEBUG - wally           - Found 1 nodes with role testnode
16:36:44 -     INFO - wally           - Start save_nodes_stage
16:36:44 -     INFO - wally           - Start connect_stage
16:36:44 -     INFO - wally           - Connecting to nodes
16:36:45 -     INFO - wally           - All nodes connected successfully
16:36:45 -     INFO - wally           - Start run_tests_stage
16:36:45 -    DEBUG - wally           - Run preparation
16:36:46 -     INFO - wally           - Prefilling file /tmp/test
16:36:46 -    DEBUG - wally           - SSH:172.17.1.2:22 Exec 'sudo fio --name=xxx --filename=/tmp/test --direct=1 --bs=4m --size=20480m --rw=write'
16:37:53 -    ERROR - wally           - XXXX
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/wally/suits/io/fio.py", line 669, in pre_run_th
    self.prefill_test_files(rossh, files, force)
  File "/usr/local/lib/python2.7/dist-packages/wally/suits/io/fio.py", line 554, in prefill_test_files
    rossh(cmd, timeout=curr_sz)
  File "/usr/local/lib/python2.7/dist-packages/wally/suits/itest.py", line 204, in closure
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/wally/ssh_utils.py", line 543, in run_over_ssh
    raise OSError(templ.format(node, cmd, code, output))
OSError: SSH:172.17.1.2:22 Cmd 'sudo fio --name=xxx --filename=/tmp/test --direct=1 --bs=4m --size=20480m --rw=write' failed with code 1. Output: xxx: (g=0): rw=write, bs=4M-4M/4M-4M/4M-4M, ioengine=sync, iodepth=1
fio-2.2.8
Starting 1 process
fio: posix_fallocate fails: No space left on device
fio: io_u error on file /tmp/test: No space left on device: write offset=20006830080, buflen=4194304
xxx: Laying out IO file(s) (1 file(s) / 20480MB)

xxx: (groupid=0, jobs=1): err=28 (file:io_u.c:1575, func=io_u error, error=No space left on device): pid=1109942: Sat Jan 23 16:37:53 2016
  write: io=19080MB, bw=293116KB/s, iops=71, runt= 66656msec
    clat (msec): min=8, max=858, avg=13.86, stdev=54.44
     lat (msec): min=8, max=858, avg=13.97, stdev=54.44
    clat percentiles (msec):
     |  1.00th=[    9],  5.00th=[    9], 10.00th=[    9], 20.00th=[    9],
     | 30.00th=[    9], 40.00th=[    9], 50.00th=[    9], 60.00th=[    9],
     | 70.00th=[    9], 80.00th=[    9], 90.00th=[   11], 95.00th=[   12],
     | 99.00th=[   44], 99.50th=[  553], 99.90th=[  824], 99.95th=[  832],
     | 99.99th=[  857]
    bw (KB  /s): min= 7062, max=484733, per=100.00%, avg=330861.00, stdev=151587.70
    lat (msec) : 10=86.52%, 20=11.57%, 50=1.01%, 250=0.04%, 500=0.27%
    lat (msec) : 750=0.31%, 1000=0.25%
  cpu          : usr=0.84%, sys=2.39%, ctx=5090, majf=0, minf=6253
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.1%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued    : total=r=0/w=4771/d=0, short=r=0/w=0/d=0, drop=r=0/w=0/d=0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
  WRITE: io=19080MB, aggrb=293115KB/s, minb=293115KB/s, maxb=293115KB/s, mint=66656msec, maxt=66656msec

Disk stats (read/write):
    dm-0: ios=0/38757, merge=0/0, ticks=0/352201, in_queue=352206, util=98.55%, aggrios=106/43805, aggrmerge=0/0, aggrticks=0/0, aggrin_queue=0, aggrutil=0.00%
    md126: ios=106/43805, merge=0/0, ticks=0/0, in_queue=0, util=0.00%, aggrios=53/43377, aggrmerge=0/427, aggrticks=237/386539, aggrin_queue=386733, aggrutil=95.51%
  sdi: ios=91/43365, merge=0/440, ticks=392/243602, in_queue=243950, util=62.21%
  sdj: ios=15/43390, merge=0/415, ticks=83/529476, in_queue=529517, util=95.51%

16:37:53 -    ERROR - wally           - During run_tests_stage
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/wally/main.py", line 124, in log_stage
    yield
  File "/usr/local/lib/python2.7/dist-packages/wally/main.py", line 276, in main
    stage(cfg, ctx)
  File "/usr/local/lib/python2.7/dist-packages/wally/run_test.py", line 481, in run_tests_stage
    for tp, res in run_tests(cfg, test_group, ctx.nodes):
  File "/usr/local/lib/python2.7/dist-packages/wally/run_test.py", line 242, in run_tests
    res = test_cls(test_cfg).run()
  File "/usr/local/lib/python2.7/dist-packages/wally/suits/io/fio.py", line 688, in run
    self.pre_run()
  File "/usr/local/lib/python2.7/dist-packages/wally/suits/io/fio.py", line 643, in pre_run
    list(pool.map(fc, self.config.nodes))
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 581, in result_iterator
    yield future.result()
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/wally/suits/io/fio.py", line 669, in pre_run_th
    self.prefill_test_files(rossh, files, force)
  File "/usr/local/lib/python2.7/dist-packages/wally/suits/io/fio.py", line 554, in prefill_test_files
    rossh(cmd, timeout=curr_sz)
  File "/usr/local/lib/python2.7/dist-packages/wally/suits/itest.py", line 204, in closure
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/wally/ssh_utils.py", line 543, in run_over_ssh
    raise OSError(templ.format(node, cmd, code, output))
OSError: SSH:172.17.1.2:22 Cmd 'sudo fio --name=xxx --filename=/tmp/test --direct=1 --bs=4m --size=20480m --rw=write' failed with code 1. Output: xxx: (g=0): rw=write, bs=4M-4M/4M-4M/4M-4M, ioengine=sync, iodepth=1
fio-2.2.8
Starting 1 process
fio: posix_fallocate fails: No space left on device
fio: io_u error on file /tmp/test: No space left on device: write offset=20006830080, buflen=4194304
xxx: Laying out IO file(s) (1 file(s) / 20480MB)

xxx: (groupid=0, jobs=1): err=28 (file:io_u.c:1575, func=io_u error, error=No space left on device): pid=1109942: Sat Jan 23 16:37:53 2016
  write: io=19080MB, bw=293116KB/s, iops=71, runt= 66656msec
    clat (msec): min=8, max=858, avg=13.86, stdev=54.44
     lat (msec): min=8, max=858, avg=13.97, stdev=54.44
    clat percentiles (msec):
     |  1.00th=[    9],  5.00th=[    9], 10.00th=[    9], 20.00th=[    9],
     | 30.00th=[    9], 40.00th=[    9], 50.00th=[    9], 60.00th=[    9],
     | 70.00th=[    9], 80.00th=[    9], 90.00th=[   11], 95.00th=[   12],
     | 99.00th=[   44], 99.50th=[  553], 99.90th=[  824], 99.95th=[  832],
     | 99.99th=[  857]
    bw (KB  /s): min= 7062, max=484733, per=100.00%, avg=330861.00, stdev=151587.70
    lat (msec) : 10=86.52%, 20=11.57%, 50=1.01%, 250=0.04%, 500=0.27%
    lat (msec) : 750=0.31%, 1000=0.25%
  cpu          : usr=0.84%, sys=2.39%, ctx=5090, majf=0, minf=6253
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.1%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued    : total=r=0/w=4771/d=0, short=r=0/w=0/d=0, drop=r=0/w=0/d=0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
  WRITE: io=19080MB, aggrb=293115KB/s, minb=293115KB/s, maxb=293115KB/s, mint=66656msec, maxt=66656msec

Disk stats (read/write):
    dm-0: ios=0/38757, merge=0/0, ticks=0/352201, in_queue=352206, util=98.55%, aggrios=106/43805, aggrmerge=0/0, aggrticks=0/0, aggrin_queue=0, aggrutil=0.00%
    md126: ios=106/43805, merge=0/0, ticks=0/0, in_queue=0, util=0.00%, aggrios=53/43377, aggrmerge=0/427, aggrticks=237/386539, aggrin_queue=386733, aggrutil=95.51%
  sdi: ios=91/43365, merge=0/440, ticks=392/243602, in_queue=243950, util=62.21%
  sdj: ios=15/43390, merge=0/415, ticks=83/529476, in_queue=529517, util=95.51%

16:37:53 -     INFO - wally           - Start disconnect_stage
16:37:53 -    DEBUG - wally           - Start utils.cleanup
16:37:53 -     INFO - wally           - All info stored into /var/wally_results/unminuted_velda
16:37:53 -    ERROR - wally           - Tests are failed. See detailed error above
